### ISSUE TITLE
Tracking data overrides urls

### ISSUE THREAD

**Issue by uncenter** [isabelroses/izrss#14] opened 2024-05-13 03:14 UTC
I have 43 URLs in my configuration but only 34 feeds are listed in the TUI. No idea why this is happening - pretty sure all of them are valid feeds? Would be nice to at least have some error handling if there are issues with the 9 missing feeds themselves.

**Comment by isabelroses** [comment] 2024-05-13 10:20
This seems to be caused by a greater bug. Being how I have implemented tracking. 

Reproduce:
1. Create `~/.config/izrss/urls` with only 2 feeds.
2. Create `~/.local/state/izrss/tracking.json` with valid data. Ensure this data only exists for 1 feed.
3. Load izrss, and notice that only 1 of the 2 feeds is actually being displayed to the screen.

**Comment by isabelroses** [comment] 2024-05-17 18:49
fixed by 55a4c90

**Closed by isabelroses** 2024-05-17 18:49 UTC
Labels: bug
